name: Backup Trigger System

on:
  schedule:
    - cron: '5,30,55 * * * *'  # প্রতি ঘন্টার 5, 30, 55 মিনিটে চেক করবে
  workflow_dispatch:

jobs:
  backup-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Retryable Self-Trigger
        run: |
          echo "Starting backup trigger..."
          retry_count=0
          max_retries=3
          success=false

          while [ $retry_count -lt $max_retries ]; do
            echo "Attempt $((retry_count+1)) to trigger the main workflow..."
            response=$(curl -s -o response.txt -w "%{http_code}" -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/blank.yml/dispatches \
              -d '{"ref":"main"}')

            cat response.txt
            if [ "$response" == "204" ]; then
              echo "Trigger succeeded!"
              success=true
              break
            else
              echo "Trigger failed with response code: $response"
              echo "Retrying in 5 seconds..."
              sleep 5
              retry_count=$((retry_count+1))
            fi
          done

          if [ "$success" = false ]; then
            echo "Failed to trigger the workflow after $max_retries attempts."
            exit 1
          fi

permissions:
  contents: write
