name: Auto Update 1

on:
  schedule:
    - cron: '*/20 * * * *'  # প্রতি ১৫ মিনিটে ট্রিগার হবে
  workflow_dispatch:  # Manually trigger করা যাবে

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Unzip Protected Script
        run: unzip -P ${{ secrets.ZIP_PASSWORD2 }} run.zip

      - name: Run Python Script
        run: python run.py

      - name: Delete Script After Run
        run: rm -f run.py

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add api.json ALL.m3u
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto update api.json and ALL.m3u"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Sleep for 20 minutes
        run: |
          echo "Sleeping for 20 minutes..."
          sleep 1200  # Sleep for 1200 seconds (20 minutes)

      - name: Trigger Next Run After Sleep
        run: |
          echo "Re-triggering workflow after 20 minutes..."
          # Any other command or action you want to trigger after sleep
          # You can use GitHub's API or any mechanism to call another workflow if needed.

permissions:
  contents: write
